---
- name: Prepare local disk for oVirt storage
  hosts: ovirthosts
  become: true
  gather_facts: true

  vars:
    storage_mount_path: "/data/ovirt-storage"
    storage_filesystem: "xfs"
    # Minimum size in GB for the storage disk
    min_disk_size_gb: 100

  tasks:
    - name: Get list of all block devices with detailed info
      ansible.builtin.shell:
        cmd: |
          lsblk -ndo NAME,SIZE,TYPE,MOUNTPOINT -b | awk '$3=="disk" {print $1","$2","$4}'
      register: all_disks_raw
      changed_when: false

    - name: Display all available disks
      ansible.builtin.debug:
        msg: "{{ all_disks_raw.stdout_lines }}"

    - name: Get detailed information for each disk
      ansible.builtin.shell:
        cmd: |
          DISK="{{ item.split(',')[0] }}"
          SIZE="{{ item.split(',')[1] }}"
          MOUNTPOINT="{{ item.split(',')[2] | default('') }}"
          
          # Check if disk itself is mounted
          DISK_MOUNTED=$(lsblk -no MOUNTPOINT /dev/$DISK 2>/dev/null | grep -v '^$' | wc -l)
          
          # Check if disk has any mounted partitions
          PART_MOUNTED=$(lsblk -no MOUNTPOINT /dev/$DISK 2>/dev/null | grep -v '^$' | head -1)
          
          # Check number of partitions
          PART_COUNT=$(lsblk -nlo NAME /dev/$DISK 2>/dev/null | tail -n +2 | wc -l)
          
          # Check for filesystem on the disk itself (not partitions)
          DISK_FS=$(blkid /dev/$DISK 2>/dev/null | wc -l)
          
          # Check for partition table
          PART_TABLE=$(parted -s /dev/$DISK print 2>/dev/null | grep -i "Partition Table:" | awk '{print $3}')
          
          echo "$DISK|$SIZE|$DISK_MOUNTED|$PART_MOUNTED|$PART_COUNT|$DISK_FS|$PART_TABLE"
      register: disk_details
      loop: "{{ all_disks_raw.stdout_lines }}"
      changed_when: false
      failed_when: false

    - name: Parse disk information
      ansible.builtin.set_fact:
        parsed_disks: >-
          {{
            disk_details.results | map(attribute='stdout') | 
            map('split', '|') |
            map('list') |
            list
          }}

    - name: Display detailed disk information
      ansible.builtin.debug:
        msg:
          - "Disk: /dev/{{ item.0 }}"
          - "Size: {{ (item.1 | int / (1024*1024*1024)) | round(2) }} GB"
          - "Disk mounted: {{ 'Yes' if item.2 | int > 0 else 'No' }}"
          - "Has mounted partitions: {{ 'Yes (' + item.3 + ')' if item.3 != '' else 'No' }}"
          - "Partition count: {{ item.4 }}"
          - "Has filesystem on disk: {{ 'Yes' if item.5 | int > 0 else 'No' }}"
          - "Partition table: {{ item.6 if item.6 != '' else 'None' }}"
          - "---"
      loop: "{{ parsed_disks }}"

    - name: Identify suitable disks
      ansible.builtin.set_fact:
        suitable_disks: >-
          {{
            parsed_disks |
            selectattr('2', 'equalto', '0') |
            selectattr('3', 'equalto', '') |
            selectattr('4', 'equalto', '0') |
            selectattr('1', 'gt', (min_disk_size_gb * 1024 * 1024 * 1024) | string) |
            list
          }}

    - name: Display suitable disks
      ansible.builtin.debug:
        msg: "Found {{ suitable_disks | length }} suitable disk(s): {{ suitable_disks | map(attribute='0') | list }}"

    - name: Fail if no suitable disk found
      ansible.builtin.fail:
        msg: |
          No suitable free disk found on {{ inventory_hostname }}.
          Requirements:
            - Disk must not be mounted
            - Disk must have no mounted partitions
            - Disk must have no partitions
            - Disk must be at least {{ min_disk_size_gb }}GB
          
          Available disks:
          {% for disk in parsed_disks %}
          - /dev/{{ disk.0 }}: {{ (disk.1 | int / (1024*1024*1024)) | round(2) }}GB, Partitions: {{ disk.4 }}, Mounted: {{ 'Yes' if disk.2 | int > 0 or disk.3 != '' else 'No' }}
          {% endfor %}
      when: suitable_disks | length == 0

    - name: Select the largest suitable disk
      ansible.builtin.set_fact:
        selected_disk: "{{ suitable_disks | sort(attribute='1', reverse=true) | first }}"

    - name: Set storage disk variable
      ansible.builtin.set_fact:
        storage_disk: "/dev/{{ selected_disk.0 }}"

    - name: Display selected disk
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Selected disk for oVirt storage:"
          - "Device: {{ storage_disk }}"
          - "Size: {{ (selected_disk.1 | int / (1024*1024*1024)) | round(2) }} GB"
          - "Partitions: {{ selected_disk.4 }}"
          - "Partition table: {{ selected_disk.6 if selected_disk.6 != '' else 'None' }}"
          - "=========================================="

    - name: Check if disk needs to be wiped
      ansible.builtin.set_fact:
        needs_wipe: "{{ selected_disk.6 != '' or selected_disk.5 | int > 0 }}"

    - name: Display wipe warning
      ansible.builtin.debug:
        msg:
          - "WARNING: Disk {{ storage_disk }} has existing partition table or filesystem signatures"
          - "Partition table: {{ selected_disk.6 }}"
          - "This will be wiped before creating the new filesystem"
      when: needs_wipe

    - name: Wipe partition table and signatures if needed
      ansible.builtin.shell:
        cmd: |
          # Wipe filesystem signatures
          wipefs -a {{ storage_disk }}
          # Zero out first and last 10MB
          dd if=/dev/zero of={{ storage_disk }} bs=1M count=10 conv=notrunc
          dd if=/dev/zero of={{ storage_disk }} bs=1M seek=$(($(blockdev --getsize64 {{ storage_disk }}) / 1048576 - 10)) count=10 conv=notrunc
          # Inform kernel of changes
          partprobe {{ storage_disk }} || true
          sleep 2
      when: needs_wipe

    - name: Display all multipath devices
      ansible.builtin.command:
        cmd: multipath -ll
      register: multipath_list
      changed_when: false
      failed_when: false

    - name: Show multipath information
      ansible.builtin.debug:
        msg: "{{ multipath_list.stdout_lines }}"
      when: multipath_list.rc == 0

    - name: Get multipath device for disk
      ansible.builtin.shell:
        cmd: |
          # Get the device name (e.g., sda)
          DISK=$(basename {{ storage_disk }})
          # Find the multipath device that uses this disk
          multipath -ll | grep -B 3 "$DISK" | head -1 | awk '{print $1}'          
      register: mpath_device
      changed_when: false
      failed_when: false

    - name: Set device to use (multipath if available, otherwise raw disk)
      ansible.builtin.set_fact:
        device_to_use: "{{ '/dev/mapper/' + mpath_device.stdout if mpath_device.stdout != '' else storage_disk }}"

    - name: Display device selection
      ansible.builtin.debug:
        msg:
          - "Raw disk: {{ storage_disk }}"
          - "Multipath device: {{ mpath_device.stdout if mpath_device.stdout != '' else 'Not found' }}"
          - "Using device: {{ device_to_use }}"

    - name: Display disk information
      ansible.builtin.command:
        cmd: lsblk {{ device_to_use }}
      register: disk_info
      changed_when: false

    - name: Show disk details
      ansible.builtin.debug:
        var: disk_info.stdout_lines

    - name: Check if filesystem already exists on device
      ansible.builtin.command:
        cmd: blkid -o value -s TYPE {{ device_to_use }}
      register: blkid_check
      changed_when: false
      failed_when: false

    - name: Display existing filesystem info
      ansible.builtin.debug:
        msg: "Existing filesystem type: {{ blkid_check.stdout }}"
      when: blkid_check.rc == 0 and blkid_check.stdout != ""

    - name: Create XFS filesystem directly on device
      community.general.filesystem:
        fstype: "{{ storage_filesystem }}"
        dev: "{{ device_to_use }}"
        force: no
      register: fs_result

    - name: Wait for filesystem to be recognized
      ansible.builtin.pause:
        seconds: 2
      when: fs_result.changed | default(false)

    - name: Get UUID of the filesystem
      ansible.builtin.command:
        cmd: blkid -s UUID -o value {{ device_to_use }}
      register: fs_uuid
      changed_when: false
      retries: 3
      delay: 2
      until: fs_uuid.rc == 0

    - name: Get filesystem label
      ansible.builtin.command:
        cmd: blkid -s LABEL -o value {{ device_to_use }}
      register: fs_label
      changed_when: false
      failed_when: false

    - name: Create mount point directory
      ansible.builtin.file:
        path: "{{ storage_mount_path }}"
        state: directory
        mode: '0755'

    - name: Display filesystem details
      ansible.builtin.debug:
        msg:
          - "Filesystem UUID: {{ fs_uuid.stdout }}"
          - "Filesystem Label: {{ fs_label.stdout if fs_label.stdout != '' else 'None' }}"
          - "Filesystem Type: {{ storage_filesystem }}"

    - name: Mount the filesystem using UUID
      ansible.posix.mount:
        path: "{{ storage_mount_path }}"
        src: "UUID={{ fs_uuid.stdout }}"
        fstype: "{{ storage_filesystem }}"
        opts: defaults,noatime,_netdev
        state: mounted

    - name: Set ownership for oVirt (vdsm user)
      ansible.builtin.file:
        path: "{{ storage_mount_path }}"
        owner: vdsm
        group: kvm
        mode: '0755'
      register: ownership_result
      ignore_errors: true

    - name: Set temporary ownership if vdsm user doesn't exist yet
      ansible.builtin.file:
        path: "{{ storage_mount_path }}"
        owner: root
        group: root
        mode: '0755'
      when: ownership_result.failed | default(false)

    - name: Display filesystem information
      ansible.builtin.command:
        cmd: df -h {{ storage_mount_path }}
      register: df_output
      changed_when: false

    - name: Display mount information
      ansible.builtin.command:
        cmd: findmnt {{ storage_mount_path }}
      register: findmnt_output
      changed_when: false

    - name: Show storage details
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Storage disk prepared successfully!"
          - "=========================================="
          - "{{ df_output.stdout_lines }}"
          - ""
          - "{{ findmnt_output.stdout_lines }}"
          - ""
          - "Mount point: {{ storage_mount_path }}"
          - "Filesystem: {{ storage_filesystem }}"
          - "Device: {{ device_to_use }}"
          - "UUID: {{ fs_uuid.stdout }}"
          - "=========================================="