---
- name: Apache webserver httpd
  hosts: servers
  become: true
  gather_facts: true

  vars:
    package_name: httpd

  tasks:
    - name: Set package_name for Ubuntu
      ansible.builtin.set_fact:
        package_name: apache2
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Install Apache
      ansible.builtin.package:
        name: "{{ package_name }}"
        state: present
